apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami2
  namespace: anael
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami2
  template:
    metadata:
      labels:
        app: whoami2
    spec:
      containers:
      - name: whoami2
        image: traefik/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami2
  namespace: anael
spec:
  selector:
    app: whoami2
  ports:
  - protocol: TCP
    port: 8080 # Service port exposed inside cluster
    targetPort: 80 # Container port
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami2-ingressroute
  namespace: anael
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`whoami2.anaeleboo.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: whoami2
      port: 8080
  tls:
    certResolver: le
